apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kv38kja9p-go
  janus-idp.io/tekton: kv38kja9p-go
  backstage.io/kubernetes-id: kv38kja9p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kv38kja9p-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
